before:
  hooks:
    - go mod tidy
builds:
  - id: valist
    main: ./cmd/valist
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
nfpms:
  - id: default
    builds:
      - valist
    formats:
      - apk
      - deb
      - rpm
    homepage: https://valist.io
    description: Web3-native software distribution.
    license: MPL-2.0
brews:
  - name: cli
    tap:
      owner: valist-io
      name: homebrew-valist
    homepage: https://valist.io
    description: Web3-native software distribution.
    license: MPL-2.0
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
