site_name: Valist Documentation
site_url: https://docs.valist.io
repo_url: https://github.com/valist-io/valist
docs_dir: src
theme:
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: img/ValistLogo128Monochrome.png
  favicon: img/favicon.ico
  name: material
  features:
    - toc.integrate
nav:
    - index.md
    - creating-an-organization.md
    - creating-a-repository.md
    - access-control.md
    - multi-factor-everything.md
    - publishing-software.md
    - fetching-and-installing-software.md
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/valist-io/valist
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/valist
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/valist_io
    - icon: fontawesome/brands/medium
      link: https://medium.com/valist
    - icon: fontawesome/brands/discord
      link: https://valist.io/discord


