site_name: Valist Documentation
site_url: https://docs.valist.io
repo_url: https://github.com/valist-io/valist
docs_dir: docs
theme:
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: img/ValistLogo128Monochrome.png
  favicon: img/favicon.ico
  name: material
  features:
    - toc.integrate
nav:
    - index.md
    - content/creating-an-organization.md
    - content/creating-a-repository.md
    - content/access-control.md
    - content/multi-factor-everything.md
    - content/publishing-software.md
    - content/fetching-and-installing-software.md
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - pymdownx.details

