name: Valist Deployment
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
env:
  DOCKER_TAG: valist/valist:latest
jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/checkout@v2
      - run: make test

  example-tests:
    name: Example Project Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/checkout@v2
        with:
          repository: valist-io/valist
          path: valist
      - name: Setup PATH
      - run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Build and install Valist
      - run: |
          cd valist && make bin
          mv valist/valist $GITHUB_WORKSPACE/bin/valist
      - name: Clone example-projects
      - run: git clone https://github.com/valist-io/example-projects
      - name: Build and publish --dryrun examples
      - run: make publish
        working-directory: ./example-projects

  publish:
    name: Multi-platform build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish multi-platform release
        uses: docker://golang:1.16
      - uses: actions/checkout@v2
      - run: make publish
