name: Valist Publish
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
env:
  DOCKER_TAG: valist/valist:latest
jobs:
  publish:
    name: Multi-platform build and publish
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          VALIST_SIGNER: ${{ secrets.VALIST_SIGNER }}
        run: make publish
